### ISSUE TITLE
update README.md

### ISSUE THREAD

**Issue by sbecuwe** [scikit-umfpack/scikit-umfpack#24]
Hello,

When using Python 3, it would be better to replace "Fürtinger" by "Fuertinger" in README.md.
If not, Python complains about the UTF-8 which could be fixed by writing
```
         with open(filename, encoding='UTF-8') as fd:
```
Regards,
Stefan

**Comment by rc** [comment]
Hi Stefan,

my Python 3.4.3 does not complain - what error do you get? Anyway, have a look at #25 if that works for you.

**Comment by sbecuwe** [comment]
Hello,

This is the error. pypandoc itself is not an issue, since it's just a warning.

```
warning: pypandoc module not found, could not convert to RST!
Traceback (most recent call last):
  File "setup.py", line 7, in read_as_rst
    from pypandoc import convert
ImportError: No module named 'pypandoc'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 23, in <module>
    LONG_DESCRIPTION    = read_as_rst('README.md')
  File "setup.py", line 14, in read_as_rst
    out = fd.read()
  File "[...]/sl6/Python/3.5.1-intel-2016a/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1047: ordinal not in range(128)
```
As indicated, #25 is a solution indeed. Thanks!

**Comment by rc** [comment]
OK, merged!
