### ISSUE TITLE
error when running with sfepy on fedora 24

### ISSUE THREAD

**Issue by HugoSiles** [scikit-umfpack/scikit-umfpack#31]
Hello,
I have instaled sfepy on fedora 24 with scikit-umfpack included. When I run the sfepy tests many of them fail some problem related to sclikit-umfpack, I know it because after uninstalling scikit-umfpack no more fails. 
I run the command: nosetests -v scikits.umfpack , and got the following errors. I don't know the  real issue, but this information may help somebody to find what is going wrong in scikit-umfpack.
[hsiles@localhost sfepy-2016.4]$ nosetests -v scikits.umfpack
test_interface.TestSolvers.test_solve_complex_umfpack ... ok
test_interface.TestSolvers.test_solve_sparse_rhs ... ok
test_interface.TestSolvers.test_solve_umfpack ... ok
test_interface.TestSolvers.test_splu_lu ... ok
test_interface.TestSolvers.test_splu_solve ... ok
test_interface.TestSolvers.test_splu_solve_sparse ... ok
test_umfpack.TestFactorization.test_complex_lu ... ok
test_umfpack.TestFactorization.test_real_lu ... ok
test_umfpack.TestScipySolvers.test_factorized_umfpack ... ERROR
test_umfpack.TestScipySolvers.test_factorized_without_umfpack ... ok
test_umfpack.TestScipySolvers.test_solve_complex_umfpack ... ERROR
test_umfpack.TestScipySolvers.test_solve_sparse_rhs ... ERROR
test_umfpack.TestScipySolvers.test_solve_umfpack ... ERROR

======================================================================
ERROR: test_umfpack.TestScipySolvers.test_factorized_umfpack
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/usr/lib/python2.7/site-packages/scikits/umfpack/tests/test_umfpack.py", line 66, in test_factorized_umfpack
    solve = linsolve.factorized(a)
  File "/usr/lib/python2.7/site-packages/scipy/sparse/linalg/dsolve/linsolve.py", line 373, in factorized
    umf.numeric(A)
  File "/usr/lib/python2.7/site-packages/scikits/umfpack/umfpack.py", line 539, in numeric
    self.symbolic(mtx)
  File "/usr/lib/python2.7/site-packages/scikits/umfpack/umfpack.py", line 509, in symbolic
    self.control, self.info)
  File "/usr/lib/python2.7/site-packages/scikits/umfpack/_umfpack.py", line 776, in umfpack_dl_symbolic
    return __umfpack.umfpack_dl_symbolic(n_row, n_col, Ap, Ai, Ax, Control, Info)
TypeError: in method 'umfpack_dl_symbolic', argument 1 of type 'SuiteSparse_long'

======================================================================
ERROR: test_umfpack.TestScipySolvers.test_solve_complex_umfpack
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/usr/lib/python2.7/site-packages/scikits/umfpack/tests/test_umfpack.py", line 43, in test_solve_complex_umfpack
    x = linsolve.spsolve(a, b)
  File "/usr/lib/python2.7/site-packages/scipy/sparse/linalg/dsolve/linsolve.py", line 139, in spsolve
    autoTranspose=True)
  File "/usr/lib/python2.7/site-packages/scikits/umfpack/umfpack.py", line 753, in linsolve
    self.numeric(mtx)
  File "/usr/lib/python2.7/site-packages/scikits/umfpack/umfpack.py", line 539, in numeric
    self.symbolic(mtx)
  File "/usr/lib/python2.7/site-packages/scikits/umfpack/umfpack.py", line 516, in symbolic
    self.control, self.info)
  File "/usr/lib/python2.7/site-packages/scikits/umfpack/_umfpack.py", line 784, in umfpack_zl_symbolic
    return __umfpack.umfpack_zl_symbolic(n_row, n_col, Ap, Ai, Ax, Az, Control, Info)
TypeError: in method 'umfpack_zl_symbolic', argument 1 of type 'SuiteSparse_long'

======================================================================
ERROR: test_umfpack.TestScipySolvers.test_solve_sparse_rhs
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/usr/lib/python2.7/site-packages/scikits/umfpack/tests/test_umfpack.py", line 59, in test_solve_sparse_rhs
    x = linsolve.spsolve(a, b)
  File "/usr/lib/python2.7/site-packages/scipy/sparse/linalg/dsolve/linsolve.py", line 139, in spsolve
    autoTranspose=True)
  File "/usr/lib/python2.7/site-packages/scikits/umfpack/umfpack.py", line 753, in linsolve
    self.numeric(mtx)
  File "/usr/lib/python2.7/site-packages/scikits/umfpack/umfpack.py", line 539, in numeric
    self.symbolic(mtx)
  File "/usr/lib/python2.7/site-packages/scikits/umfpack/umfpack.py", line 509, in symbolic
    self.control, self.info)
  File "/usr/lib/python2.7/site-packages/scikits/umfpack/_umfpack.py", line 776, in umfpack_dl_symbolic
    return __umfpack.umfpack_dl_symbolic(n_row, n_col, Ap, Ai, Ax, Control, Info)
TypeError: in method 'umfpack_dl_symbolic', argument 1 of type 'SuiteSparse_long'

======================================================================
ERROR: test_umfpack.TestScipySolvers.test_solve_umfpack
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/usr/lib/python2.7/site-packages/scikits/umfpack/tests/test_umfpack.py", line 51, in test_solve_umfpack
    x = linsolve.spsolve(a, b)
  File "/usr/lib/python2.7/site-packages/scipy/sparse/linalg/dsolve/linsolve.py", line 139, in spsolve
    autoTranspose=True)
  File "/usr/lib/python2.7/site-packages/scikits/umfpack/umfpack.py", line 753, in linsolve
    self.numeric(mtx)
  File "/usr/lib/python2.7/site-packages/scikits/umfpack/umfpack.py", line 539, in numeric
    self.symbolic(mtx)
  File "/usr/lib/python2.7/site-packages/scikits/umfpack/umfpack.py", line 509, in symbolic
    self.control, self.info)
  File "/usr/lib/python2.7/site-packages/scikits/umfpack/_umfpack.py", line 776, in umfpack_dl_symbolic
    return __umfpack.umfpack_dl_symbolic(n_row, n_col, Ap, Ai, Ax, Control, Info)
TypeError: in method 'umfpack_dl_symbolic', argument 1 of type 'SuiteSparse_long'

----------------------------------------------------------------------
Ran 13 tests in 0.069s

FAILED (errors=4)

Cheers Hugo

**Comment by rc** [comment]
This should be fixed now by #23.
