### ISSUE TITLE
tests failing on 32-bit platforms due to long indices

### ISSUE THREAD

**Issue by rgommers** [scikit-umfpack/scikit-umfpack#34]
These are the test errors I get on 32-bit Linux (Ubuntu 14.04), Python 2.7, gcc 4.8.4, SWIG 2.0.11.

From a quick search, may be related to gh-23. Uncovered when testing https://github.com/scipy/scipy/pull/7498 

    $ nosetests -v scikits.umfpack
    test_interface.TestSolvers.test_solve_complex_umfpack ... ok
    test_interface.TestSolvers.test_solve_sparse_rhs ... ok
    test_interface.TestSolvers.test_solve_umfpack ... ok
    test_interface.TestSolvers.test_splu_lu ... ok
    test_interface.TestSolvers.test_splu_solve ... ok
    test_interface.TestSolvers.test_splu_solve_sparse ... ok
    test_umfpack.TestFactorization.test_complex_lu ... ok
    test_umfpack.TestFactorization.test_real_lu ... ok
    test_umfpack.TestScipySolvers.test_factorized_umfpack ... ERROR
    test_umfpack.TestScipySolvers.test_factorized_without_umfpack ... ok
    test_umfpack.TestScipySolvers.test_solve_complex_umfpack ... ERROR
    test_umfpack.TestScipySolvers.test_solve_sparse_rhs ... ERROR
    test_umfpack.TestScipySolvers.test_solve_umfpack ... ERROR

    ======================================================================
    ERROR: test_umfpack.TestScipySolvers.test_factorized_umfpack
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/home/rgommers/.local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
        self.test(*self.arg)
      File "/home/rgommers/.local/lib/python2.7/site-packages/scikits/umfpack/tests/test_umfpack.py", line 66, in test_factorized_umfpack
        solve = linsolve.factorized(a)
      File "/home/rgommers/Code/scipy/scipy/sparse/linalg/dsolve/linsolve.py", line 418, in factorized
        umf.numeric(A)
      File "/home/rgommers/.local/lib/python2.7/site-packages/scikits/umfpack/umfpack.py", line 539, in numeric
        self.symbolic(mtx)
      File "/home/rgommers/.local/lib/python2.7/site-packages/scikits/umfpack/umfpack.py", line 509, in symbolic
        self.control, self.info)
      File "/home/rgommers/.local/lib/python2.7/site-packages/scikits/umfpack/_umfpack.py", line 465, in umfpack_dl_symbolic
        return __umfpack.umfpack_dl_symbolic(*args)
    TypeError: in method 'umfpack_dl_symbolic', argument 1 of type 'SuiteSparse_long'

    ======================================================================
    ERROR: test_umfpack.TestScipySolvers.test_solve_complex_umfpack
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/home/rgommers/.local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
        self.test(*self.arg)
      File "/home/rgommers/.local/lib/python2.7/site-packages/scikits/umfpack/tests/test_umfpack.py", line 43, in test_solve_complex_umfpack
        x = linsolve.spsolve(a, b)
      File "/home/rgommers/Code/scipy/scipy/sparse/linalg/dsolve/linsolve.py", line 159, in spsolve
        autoTranspose=True)
      File "/home/rgommers/.local/lib/python2.7/site-packages/scikits/umfpack/umfpack.py", line 753, in linsolve
        self.numeric(mtx)
      File "/home/rgommers/.local/lib/python2.7/site-packages/scikits/umfpack/umfpack.py", line 539, in numeric
        self.symbolic(mtx)
      File "/home/rgommers/.local/lib/python2.7/site-packages/scikits/umfpack/umfpack.py", line 516, in symbolic
        self.control, self.info)
      File "/home/rgommers/.local/lib/python2.7/site-packages/scikits/umfpack/_umfpack.py", line 480, in umfpack_zl_symbolic
        return __umfpack.umfpack_zl_symbolic(*args)
    TypeError: in method 'umfpack_zl_symbolic', argument 1 of type 'SuiteSparse_long'

    ======================================================================
    ERROR: test_umfpack.TestScipySolvers.test_solve_sparse_rhs
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/home/rgommers/.local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
        self.test(*self.arg)
      File "/home/rgommers/.local/lib/python2.7/site-packages/scikits/umfpack/tests/test_umfpack.py", line 59, in test_solve_sparse_rhs
        x = linsolve.spsolve(a, b)
      File "/home/rgommers/Code/scipy/scipy/sparse/linalg/dsolve/linsolve.py", line 159, in spsolve
        autoTranspose=True)
      File "/home/rgommers/.local/lib/python2.7/site-packages/scikits/umfpack/umfpack.py", line 753, in linsolve
        self.numeric(mtx)
      File "/home/rgommers/.local/lib/python2.7/site-packages/scikits/umfpack/umfpack.py", line 539, in numeric
        self.symbolic(mtx)
      File "/home/rgommers/.local/lib/python2.7/site-packages/scikits/umfpack/umfpack.py", line 509, in symbolic
        self.control, self.info)
      File "/home/rgommers/.local/lib/python2.7/site-packages/scikits/umfpack/_umfpack.py", line 465, in umfpack_dl_symbolic
        return __umfpack.umfpack_dl_symbolic(*args)
    TypeError: in method 'umfpack_dl_symbolic', argument 1 of type 'SuiteSparse_long'

    ======================================================================
    ERROR: test_umfpack.TestScipySolvers.test_solve_umfpack
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/home/rgommers/.local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
        self.test(*self.arg)
      File "/home/rgommers/.local/lib/python2.7/site-packages/scikits/umfpack/tests/test_umfpack.py", line 51, in test_solve_umfpack
        x = linsolve.spsolve(a, b)
      File "/home/rgommers/Code/scipy/scipy/sparse/linalg/dsolve/linsolve.py", line 159, in spsolve
        autoTranspose=True)
      File "/home/rgommers/.local/lib/python2.7/site-packages/scikits/umfpack/umfpack.py", line 753, in linsolve
        self.numeric(mtx)
      File "/home/rgommers/.local/lib/python2.7/site-packages/scikits/umfpack/umfpack.py", line 539, in numeric
        self.symbolic(mtx)
      File "/home/rgommers/.local/lib/python2.7/site-packages/scikits/umfpack/umfpack.py", line 509, in symbolic
        self.control, self.info)
      File "/home/rgommers/.local/lib/python2.7/site-packages/scikits/umfpack/_umfpack.py", line 465, in umfpack_dl_symbolic
        return __umfpack.umfpack_dl_symbolic(*args)
    TypeError: in method 'umfpack_dl_symbolic', argument 1 of type 'SuiteSparse_long'

    ----------------------------------------------------------------------
    Ran 13 tests in 0.062s

    FAILED (errors=4)

**Comment by rc** [comment]
Thanks for reporting that, I agree that it might be related to #23. I will try to debug it.

**Comment by rc** [comment]
@rgommers, I could you try https://github.com/scikit-umfpack/scikit-umfpack/pull/23/commits/d0d5fd1c96c1b96d7b97f06cd8c28ccba7ea9c92, if that fixes the issue?

Explanation: According to https://github.com/PetterS/SuiteSparse/tree/master/SuiteSparse_config:

```
A note on the update to SuiteSparse Version 4.0.0:  The SuiteSparse_long macro
defines an integer that is 64-bits in size on 64-bit platforms, and 32-bits on
32-bit platforms.  It was formerly called UF_long, but UF_long has been removed
because of potential name conflicts.  UF_long is still available to user codes,
but it can now be safely #undef'd in case of name conflicts in user code.
Future codes should use SuiteSparse_long in place of UF_long.
```

To try that out in the branch of #23, I defined:
```
typedef long UF_long;
typedef long SuiteSparse_long;
```

in ``scikits/umfpack/umfpack.i`` so that both cases are covered. As a result, #23 tests pass now, but I am not sure about the portability of the above solution. Any thoughts?

**Comment by rc** [comment]
@rgommers I have just rebased https://github.com/rc/scikit-umfpack-rc/tree/long-indices to master, travis tests pass. Is there a way to tell Travis CI to test on 32bit systems too?

**Comment by rgommers** [comment]
> Is there a way to tell Travis CI to test on 32bit systems too?

That's not completely trivial. I know of two ways:
- how numpy does it: https://github.com/numpy/numpy/blob/master/tools/travis-test.sh#L175
- using multibuild: https://github.com/matthew-brett/multibuild#utilities-for-building-on-travis-ci-with-osx-and-linux

@matthewbrett would you recommend stealing the relevant bit of ``multibuild`` for projects testing 32-bit builds, or use the numpy way?

SciPy could also use some 32-bit testing...

**Comment by rgommers** [comment]
Sorry, looks like it'll take me a while to test this. Have tried for half an hour earlier today, but I now get weird LAPACK related build issues on my system, not sure what changed (also happens for older versions, so not related to your changes).

**Comment by rc** [comment]
No problem - I get to it only as other tasks permit.

**Comment by rgommers** [comment]
That didn't quite work, still getting errors like

    File "/home/rgommers/.local/lib/python2.7/site-packages/scikits/umfpack/_umfpack.py", line 465, in umfpack_dl_symbolic
        return __umfpack.umfpack_dl_symbolic(*args)
    TypeError: in method 'umfpack_dl_symbolic', argument 1 of type 'SuiteSparse_long'

I don't think that change anything, because ``UF_long`` is defined as ``SuiteSparse_long``:
https://github.com/PetterS/SuiteSparse/blob/master/SuiteSparse_config/SuiteSparse_config.h#L70
Also, ``UF_long`` is deprecated, so don't introduce it.

I'll see if I can figure out what it should be.

**Comment by rgommers** [comment]
Okay, that did fix it it looks like - just the tests had an issue still. That should be fixed by https://github.com/rgommers/scikit-umfpack/commit/a1956b216e8b

Short summary: tests assumed ``long`` and ``int64`` are the same, which is clearly not true on 32-bit platforms. So skip tests for int64 indices on 32-bit platforms, and rename stuff to ``int64``.

I've verified that https://github.com/scipy/scipy/pull/7498 now also passes all the ``sparse.linalg`` tests.

**Comment by rc** [comment]
@rgommers thanks! I am back to computer, looking at it. I will split the WIP commit in https://github.com/rc/scikit-umfpack-rc/tree/long-indices, add proper messages, and then merge your commit with the test skipping, OK?

**Comment by rgommers** [comment]
That sounds good to me!

**Comment by rc** [comment]
It is in #23, and Travis CI tests pass (on 64 bit platforms). I would merge it now to master (provided the scipy tests are OK), and eventually add the 32-bit system tests later, in another PR - what do you think?

**Comment by rgommers** [comment]
That sounds good to me. I've run the ``scipy.sparse`` tests with my commit on top of gh-23, so should be OK as is.
