### ISSUE TITLE
Build fails with python-3.6: UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1064

### ISSUE THREAD

**Issue by yurivict** [scikit-umfpack/scikit-umfpack#53]
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "setup.py", line 7, in <module>
    LONG_DESCRIPTION    = open('README.rst').read()
  File "/usr/local/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1064: ordinal not in range(128)
*** Error code 1
```

**Comment by rc** [comment]
Thanks! Could you check whether #54 fixes the problem?
