### ISSUE TITLE
AttributeError: 'module' object has no attribute 'UMFPACK_INFO'

### ISSUE THREAD

**Issue by romeric** [scikit-umfpack/scikit-umfpack#59]
Travis has been recently failing on us ([project Florence](https://github.com/romeric/florence)) with a scikit-umfpack error on python 2.7 under Ubuntu 14.04. UMFPack is installed using the usual (`libsuitesparse-dev`) protocol. Here is the short version of the error log:
~~~
ERROR: test.test_examples
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/build/romeric/florence/tests/test.py", line 199, in test_examples
    simple_laplace(optimise=False, recompute_sparsity_pattern=True, squeeze_sparsity_pattern=False)
  File "../examples/simple_laplace/simple_laplace.py", line 45, in simple_laplace
    mesh=mesh)
  File "/home/travis/build/romeric/florence/Florence/Solver/FEMSolver.py", line 498, in Solve
    formulation, mesh, function_spaces, solver, contact_formulation=contact_formulation)
  File "/home/travis/build/romeric/florence/Florence/Solver/FEMSolver.py", line 215, in __checkdata__
    solver = LinearSolver(linear_solver="direct", linear_solver_type="umfpack", geometric_discretisation=mesh.element_type)
  File "/home/travis/build/romeric/florence/Florence/Solver/Solver.py", line 75, in __init__
    from scikits.umfpack import spsolve
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/scikits/umfpack/__init__.py", line 12, in <module>
    from .umfpack import *
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/scikits/umfpack/umfpack.py", line 130, in <module>
    from . import _umfpack as _um
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/scikits/umfpack/_umfpack.py", line 98, in <module>
    UMFPACK_INFO = __umfpack.UMFPACK_INFO
AttributeError: 'module' object has no attribute 'UMFPACK_INFO'
~~~

The full travis log can be found [here](https://travis-ci.com/romeric/florence/jobs/158503075). The problem is very recent and did not exist maybe a couple of weeks ago. The issue does not appear under python 3.5/3.6/3.7. Has anything changed in the recent release (0.3.2)?

**Comment by rc** [comment]
No, 0.3.2 contains only some minor modifications w.r.t. 0.3.1. Could you try forcing the 0.3.1 version in your travis setup?

**Comment by romeric** [comment]
Forcing travis to 0.3.1 version does actually solve the problem. Log [here](https://travis-ci.com/romeric/florence/jobs/158740681).

**Comment by rc** [comment]
OK. So I suspect that the 0.3.2 manylinux wheels that pip installs might be wrong, see also https://github.com/scikit-umfpack/scikit-umfpack-wheels/issues/2. I will try to investigate, but I am not very good in solving CI issues, so for the moment, you can either pip install the 0.3.1, or build 0.3.2 from sources.
