### ISSUE TITLE
Only version 0.3.1 works and only on Python 3.6 (Windows 10 x64)

### ISSUE THREAD

**Issue by constructor-s** [scikit-umfpack/scikit-umfpack#64]
I have tried many different combinations between different Python versions using Anaconda environments and installing numpy from conda, conda-forge, or pip, on Windows 10, but the only combination that seems to work consistently for me is Python 3.6 with numpy from pip and `scikit-umfpack==0.3.1`:

```batchfile
>conda create -n p36_pip python=3.6
>conda activate p36_pip

:: Version 0.3.2 does not work
>pip install scikit-umfpack==0.3.2
Processing c:\users\USERNAME\appdata\local\pip\cache\wheels\d2\dc\dd\82ca79368ca3cb77c581785b4f190883c8afe3b29cb7a94c66\scikit_umfpack-0.3.2-cp36-cp36m-win_amd64.whl
Collecting numpy>=1.14.0
  Using cached numpy-1.18.4-cp36-cp36m-win_amd64.whl (12.8 MB)
Collecting scipy>=1.0.0rc1
  Using cached scipy-1.4.1-cp36-cp36m-win_amd64.whl (30.8 MB)
Installing collected packages: numpy, scipy, scikit-umfpack
Successfully installed numpy-1.18.4 scikit-umfpack-0.3.2 scipy-1.4.1

>python -c "from scikits.umfpack import spsolve, splu"
Traceback (most recent call last):
  File "C:\tools\Anaconda3\envs\p36_pip\lib\site-packages\scikits\umfpack\_umfpack.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('__umfpack', [dirname(__file__)])
  File "C:\tools\Anaconda3\envs\p36_pip\lib\imp.py", line 297, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '__umfpack'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\tools\Anaconda3\envs\p36_pip\lib\site-packages\scikits\umfpack\__init__.py", line 12, in <module>
    from .umfpack import *
  File "C:\tools\Anaconda3\envs\p36_pip\lib\site-packages\scikits\umfpack\umfpack.py", line 130, in <module>
    from . import _umfpack as _um
  File "C:\tools\Anaconda3\envs\p36_pip\lib\site-packages\scikits\umfpack\_umfpack.py", line 28, in <module>
    __umfpack = swig_import_helper()
  File "C:\tools\Anaconda3\envs\p36_pip\lib\site-packages\scikits\umfpack\_umfpack.py", line 20, in swig_import_helper
    import __umfpack
ModuleNotFoundError: No module named '__umfpack'

:: Version 0.3.1 works
>pip install scikit-umfpack==0.3.1
Collecting scikit-umfpack==0.3.1
  Using cached scikit_umfpack-0.3.1-cp36-none-win_amd64.whl (3.6 MB)
Requirement already satisfied: numpy>=1.12.1 in c:\tools\anaconda3\envs\p36_pip\lib\site-packages (from scikit-umfpack==0.3.1) (1.18.4)
Requirement already satisfied: scipy>=1.0.0rc1 in c:\tools\anaconda3\envs\p36_pip\lib\site-packages (from scikit-umfpack==0.3.1) (1.4.1)
Installing collected packages: scikit-umfpack
  Attempting uninstall: scikit-umfpack
    Found existing installation: scikit-umfpack 0.3.2
    Uninstalling scikit-umfpack-0.3.2:
      Successfully uninstalled scikit-umfpack-0.3.2
Successfully installed scikit-umfpack-0.3.1

>python -c "from scikits.umfpack import spsolve, splu"
:: No error
```

The following is my speculation: 

With Python 3.6-3.8, it seems to me that with `scikit-umfpack==0.3.2` it simply downloads the latest wheel which is incompatible with either the Python version or latest numpy version, or both. 

With Python 3.6 and `scikit-umfpack==0.3.1`, there is an existing wheel for Windows that works with even the latest numpy version in May 2020.

With Python 3.7-3.8 and `scikit-umfpack==0.3.1`, there is no existing wheel. When I attempt to build (I have suitesparse built with vcpkg), this is as far as I get:

```batchfile
>pip install scikit-umfpack==0.3.1
Collecting scikit-umfpack==0.3.1
  Using cached scikit-umfpack-0.3.1.tar.gz (24 kB)
Requirement already satisfied: numpy>=1.18.4 in c:\tools\anaconda3\envs\p37_pip\lib\site-packages (from scikit-umfpack==0.3.1) (1.18.4)
Requirement already satisfied: scipy>=1.0.0rc1 in c:\tools\anaconda3\envs\p37_pip\lib\site-packages (from scikit-umfpack==0.3.1) (1.4.1)
Building wheels for collected packages: scikit-umfpack
  Building wheel for scikit-umfpack (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\tools\Anaconda3\envs\p37_pip\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\USERNAME\\AppData\\Local\\Temp\\pip-install-l6bvkytm\\scikit-umfpack\\setup.py'"'"'; __file__='"'"'C:\\Users\\USERNAME\\AppData\\Local\\Temp\\pip-install-l6bvkytm\\scikit-umfpack\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\USERNAME\AppData\Local\Temp\pip-wheel-zat_g0am'
       cwd: C:\Users\USERNAME\AppData\Local\Temp\pip-install-l6bvkytm\scikit-umfpack\
  Complete output (121 lines):
  C:\Users\USERNAME\AppData\Local\Temp\pip-install-l6bvkytm\scikit-umfpack\setup.py:56: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
    import imp
  umfpack_info:
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
  amd_info:
    libraries amd not found in ['C:\\tools\\Anaconda3\\envs\\p37_pip\\lib', 'C:\\', 'C:\\tools\\Anaconda3\\envs\\p37_pip\\libs', 'C:\\tools\\Anaconda3\\Library\\lib']
    NOT AVAILABLE

    FOUND:
      libraries = ['libumfpack', 'libumfpack']
      library_dirs = ['C:\\vcpkg\\installed\\x64-windows\\lib']
      include_dirs = ['C:\\vcpkg\\installed\\x64-windows\\include\\suitesparse']
      define_macros = [('SCIPY_UMFPACK_H', None)]
      swig_opts = ['-IC:\\vcpkg\\installed\\x64-windows\\include\\suitesparse']

  blas_opt_info:
  blas_mkl_info:
    libraries mkl_rt not found in ['C:\\tools\\Anaconda3\\envs\\p37_pip\\lib', 'C:\\', 'C:\\tools\\Anaconda3\\envs\\p37_pip\\libs', 'C:\\tools\\Anaconda3\\Library\\lib']
    NOT AVAILABLE

  blis_info:
    libraries blis not found in ['C:\\tools\\Anaconda3\\envs\\p37_pip\\lib', 'C:\\', 'C:\\tools\\Anaconda3\\envs\\p37_pip\\libs', 'C:\\tools\\Anaconda3\\Library\\lib']
    NOT AVAILABLE

  openblas_info:
    libraries openblas not found in ['C:\\tools\\Anaconda3\\envs\\p37_pip\\lib', 'C:\\', 'C:\\tools\\Anaconda3\\envs\\p37_pip\\libs', 'C:\\tools\\Anaconda3\\Library\\lib']
  get_default_fcompiler: matching types: '['gnu', 'intelv', 'absoft', 'compaqv', 'intelev', 'gnu95', 'g95', 'intelvem', 'intelem', 'flang']'
  customize GnuFCompiler
  Could not locate executable g77
  Could not locate executable f77
  customize IntelVisualFCompiler
  Could not locate executable ifort
  Could not locate executable ifl
  customize AbsoftFCompiler
  Could not locate executable f90
  customize CompaqVisualFCompiler
  Could not locate executable DF
  customize IntelItaniumVisualFCompiler
  Could not locate executable efl
  customize Gnu95FCompiler
  Could not locate executable gfortran
  Could not locate executable f95
  customize G95FCompiler
  Could not locate executable g95
  customize IntelEM64VisualFCompiler
  customize IntelEM64TFCompiler
  Could not locate executable efort
  Could not locate executable efc
  customize PGroupFlangCompiler
  Could not locate executable flang
  don't know how to compile Fortran code on platform 'nt'
    NOT AVAILABLE

  atlas_3_10_blas_threads_info:
  Setting PTATLAS=ATLAS
    libraries tatlas not found in ['C:\\tools\\Anaconda3\\envs\\p37_pip\\lib', 'C:\\', 'C:\\tools\\Anaconda3\\envs\\p37_pip\\libs', 'C:\\tools\\Anaconda3\\Library\\lib']
    NOT AVAILABLE

  atlas_3_10_blas_info:
    libraries satlas not found in ['C:\\tools\\Anaconda3\\envs\\p37_pip\\lib', 'C:\\', 'C:\\tools\\Anaconda3\\envs\\p37_pip\\libs', 'C:\\tools\\Anaconda3\\Library\\lib']
    NOT AVAILABLE

  atlas_blas_threads_info:
  Setting PTATLAS=ATLAS
    libraries ptf77blas,ptcblas,atlas not found in ['C:\\tools\\Anaconda3\\envs\\p37_pip\\lib', 'C:\\', 'C:\\tools\\Anaconda3\\envs\\p37_pip\\libs', 'C:\\tools\\Anaconda3\\Library\\lib']
    NOT AVAILABLE

  atlas_blas_info:
    libraries f77blas,cblas,atlas not found in ['C:\\tools\\Anaconda3\\envs\\p37_pip\\lib', 'C:\\', 'C:\\tools\\Anaconda3\\envs\\p37_pip\\libs', 'C:\\tools\\Anaconda3\\Library\\lib']
    NOT AVAILABLE

  accelerate_info:
    NOT AVAILABLE

  C:\tools\Anaconda3\envs\p37_pip\lib\site-packages\numpy\distutils\system_info.py:1896: UserWarning:
      Optimized (vendor) Blas libraries are not found.
      Falls back to netlib Blas library which has worse performance.
      A better performance should be easily gained by switching
      Blas library.
    if self._calc_info(blas):
  blas_info:
    libraries blas not found in ['C:\\tools\\Anaconda3\\envs\\p37_pip\\lib', 'C:\\', 'C:\\tools\\Anaconda3\\envs\\p37_pip\\libs', 'C:\\tools\\Anaconda3\\Library\\lib']
    NOT AVAILABLE

  C:\tools\Anaconda3\envs\p37_pip\lib\site-packages\numpy\distutils\system_info.py:1896: UserWarning:
      Blas (http://www.netlib.org/blas/) libraries not found.
      Directories to search for the libraries can be specified in the
      numpy/distutils/site.cfg file (section [blas]) or by setting
      the BLAS environment variable.
    if self._calc_info(blas):
  blas_src_info:
    NOT AVAILABLE

  C:\tools\Anaconda3\envs\p37_pip\lib\site-packages\numpy\distutils\system_info.py:1896: UserWarning:
      Blas (http://www.netlib.org/blas/) sources not found.
      Directories to search for the sources can be specified in the
      numpy/distutils/site.cfg file (section [blas_src]) or by setting
      the BLAS_SRC environment variable.
    if self._calc_info(blas):
    NOT AVAILABLE

  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\USERNAME\AppData\Local\Temp\pip-install-l6bvkytm\scikit-umfpack\setup.py", line 250, in <module>
      setup_package()
    File "C:\Users\USERNAME\AppData\Local\Temp\pip-install-l6bvkytm\scikit-umfpack\setup.py", line 247, in setup_package
      setup(**metadata)
    File "C:\tools\Anaconda3\envs\p37_pip\lib\site-packages\numpy\distutils\core.py", line 137, in setup
      config = configuration()
    File "C:\Users\USERNAME\AppData\Local\Temp\pip-install-l6bvkytm\scikit-umfpack\setup.py", line 143, in configuration
      config.add_subpackage('scikits.umfpack')
    File "C:\tools\Anaconda3\envs\p37_pip\lib\site-packages\numpy\distutils\misc_util.py", line 1035, in add_subpackage
      caller_level = 2)
    File "C:\tools\Anaconda3\envs\p37_pip\lib\site-packages\numpy\distutils\misc_util.py", line 1004, in get_subpackage
      caller_level = caller_level + 1)
    File "C:\tools\Anaconda3\envs\p37_pip\lib\site-packages\numpy\distutils\misc_util.py", line 941, in _get_configuration_from_setup_py
      config = setup_module.configuration(*args)
    File "scikits\umfpack\setup.py", line 36, in configuration
      build_info['libraries'].remove('umfpack')
  ValueError: list.remove(x): x not in list
  ----------------------------------------
  ERROR: Failed building wheel for scikit-umfpack
  Running setup.py clean for scikit-umfpack
Failed to build scikit-umfpack
Installing collected packages: scikit-umfpack
    Running setup.py install for scikit-umfpack ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\tools\Anaconda3\envs\p37_pip\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\USERNAME\\AppData\\Local\\Temp\\pip-install-l6bvkytm\\scikit-umfpack\\setup.py'"'"'; __file__='"'"'C:\\Users\\USERNAME\\AppData\\Local\\Temp\\pip-install-l6bvkytm\\scikit-umfpack\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\USERNAME\AppData\Local\Temp\pip-record-iwvssjic\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\tools\Anaconda3\envs\p37_pip\Include\scikit-umfpack'
         cwd: C:\Users\USERNAME\AppData\Local\Temp\pip-install-l6bvkytm\scikit-umfpack\
    Complete output (121 lines):
    C:\Users\USERNAME\AppData\Local\Temp\pip-install-l6bvkytm\scikit-umfpack\setup.py:56: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
      import imp
    umfpack_info:
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
    amd_info:
      libraries amd not found in ['C:\\tools\\Anaconda3\\envs\\p37_pip\\lib', 'C:\\', 'C:\\tools\\Anaconda3\\envs\\p37_pip\\libs', 'C:\\tools\\Anaconda3\\Library\\lib']
      NOT AVAILABLE

      FOUND:
        libraries = ['libumfpack', 'libumfpack']
        library_dirs = ['C:\\vcpkg\\installed\\x64-windows\\lib']
        include_dirs = ['C:\\vcpkg\\installed\\x64-windows\\include\\suitesparse']
        define_macros = [('SCIPY_UMFPACK_H', None)]
        swig_opts = ['-IC:\\vcpkg\\installed\\x64-windows\\include\\suitesparse']

    blas_opt_info:
    blas_mkl_info:
      libraries mkl_rt not found in ['C:\\tools\\Anaconda3\\envs\\p37_pip\\lib', 'C:\\', 'C:\\tools\\Anaconda3\\envs\\p37_pip\\libs', 'C:\\tools\\Anaconda3\\Library\\lib']
      NOT AVAILABLE

    blis_info:
      libraries blis not found in ['C:\\tools\\Anaconda3\\envs\\p37_pip\\lib', 'C:\\', 'C:\\tools\\Anaconda3\\envs\\p37_pip\\libs', 'C:\\tools\\Anaconda3\\Library\\lib']
      NOT AVAILABLE

    openblas_info:
      libraries openblas not found in ['C:\\tools\\Anaconda3\\envs\\p37_pip\\lib', 'C:\\', 'C:\\tools\\Anaconda3\\envs\\p37_pip\\libs', 'C:\\tools\\Anaconda3\\Library\\lib']
    get_default_fcompiler: matching types: '['gnu', 'intelv', 'absoft', 'compaqv', 'intelev', 'gnu95', 'g95', 'intelvem', 'intelem', 'flang']'
    customize GnuFCompiler
    Could not locate executable g77
    Could not locate executable f77
    customize IntelVisualFCompiler
    Could not locate executable ifort
    Could not locate executable ifl
    customize AbsoftFCompiler
    Could not locate executable f90
    customize CompaqVisualFCompiler
    Could not locate executable DF
    customize IntelItaniumVisualFCompiler
    Could not locate executable efl
    customize Gnu95FCompiler
    Could not locate executable gfortran
    Could not locate executable f95
    customize G95FCompiler
    Could not locate executable g95
    customize IntelEM64VisualFCompiler
    customize IntelEM64TFCompiler
    Could not locate executable efort
    Could not locate executable efc
    customize PGroupFlangCompiler
    Could not locate executable flang
    don't know how to compile Fortran code on platform 'nt'
      NOT AVAILABLE

    atlas_3_10_blas_threads_info:
    Setting PTATLAS=ATLAS
      libraries tatlas not found in ['C:\\tools\\Anaconda3\\envs\\p37_pip\\lib', 'C:\\', 'C:\\tools\\Anaconda3\\envs\\p37_pip\\libs', 'C:\\tools\\Anaconda3\\Library\\lib']
      NOT AVAILABLE

    atlas_3_10_blas_info:
      libraries satlas not found in ['C:\\tools\\Anaconda3\\envs\\p37_pip\\lib', 'C:\\', 'C:\\tools\\Anaconda3\\envs\\p37_pip\\libs', 'C:\\tools\\Anaconda3\\Library\\lib']
      NOT AVAILABLE

    atlas_blas_threads_info:
    Setting PTATLAS=ATLAS
      libraries ptf77blas,ptcblas,atlas not found in ['C:\\tools\\Anaconda3\\envs\\p37_pip\\lib', 'C:\\', 'C:\\tools\\Anaconda3\\envs\\p37_pip\\libs', 'C:\\tools\\Anaconda3\\Library\\lib']
      NOT AVAILABLE

    atlas_blas_info:
      libraries f77blas,cblas,atlas not found in ['C:\\tools\\Anaconda3\\envs\\p37_pip\\lib', 'C:\\', 'C:\\tools\\Anaconda3\\envs\\p37_pip\\libs', 'C:\\tools\\Anaconda3\\Library\\lib']
      NOT AVAILABLE

    accelerate_info:
      NOT AVAILABLE

    C:\tools\Anaconda3\envs\p37_pip\lib\site-packages\numpy\distutils\system_info.py:1896: UserWarning:
        Optimized (vendor) Blas libraries are not found.
        Falls back to netlib Blas library which has worse performance.
        A better performance should be easily gained by switching
        Blas library.
      if self._calc_info(blas):
    blas_info:
      libraries blas not found in ['C:\\tools\\Anaconda3\\envs\\p37_pip\\lib', 'C:\\', 'C:\\tools\\Anaconda3\\envs\\p37_pip\\libs', 'C:\\tools\\Anaconda3\\Library\\lib']
      NOT AVAILABLE

    C:\tools\Anaconda3\envs\p37_pip\lib\site-packages\numpy\distutils\system_info.py:1896: UserWarning:
        Blas (http://www.netlib.org/blas/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [blas]) or by setting
        the BLAS environment variable.
      if self._calc_info(blas):
    blas_src_info:
      NOT AVAILABLE

    C:\tools\Anaconda3\envs\p37_pip\lib\site-packages\numpy\distutils\system_info.py:1896: UserWarning:
        Blas (http://www.netlib.org/blas/) sources not found.
        Directories to search for the sources can be specified in the
        numpy/distutils/site.cfg file (section [blas_src]) or by setting
        the BLAS_SRC environment variable.
      if self._calc_info(blas):
      NOT AVAILABLE

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\USERNAME\AppData\Local\Temp\pip-install-l6bvkytm\scikit-umfpack\setup.py", line 250, in <module>
        setup_package()
      File "C:\Users\USERNAME\AppData\Local\Temp\pip-install-l6bvkytm\scikit-umfpack\setup.py", line 247, in setup_package
        setup(**metadata)
      File "C:\tools\Anaconda3\envs\p37_pip\lib\site-packages\numpy\distutils\core.py", line 137, in setup
        config = configuration()
      File "C:\Users\USERNAME\AppData\Local\Temp\pip-install-l6bvkytm\scikit-umfpack\setup.py", line 143, in configuration
        config.add_subpackage('scikits.umfpack')
      File "C:\tools\Anaconda3\envs\p37_pip\lib\site-packages\numpy\distutils\misc_util.py", line 1035, in add_subpackage
        caller_level = 2)
      File "C:\tools\Anaconda3\envs\p37_pip\lib\site-packages\numpy\distutils\misc_util.py", line 1004, in get_subpackage
        caller_level = caller_level + 1)
      File "C:\tools\Anaconda3\envs\p37_pip\lib\site-packages\numpy\distutils\misc_util.py", line 941, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "scikits\umfpack\setup.py", line 36, in configuration
        build_info['libraries'].remove('umfpack')
    ValueError: list.remove(x): x not in list
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\tools\Anaconda3\envs\p37_pip\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\USERNAME\\AppData\\Local\\Temp\\pip-install-l6bvkytm\\scikit-umfpack\\setup.py'"'"'; __file__='"'"'C:\\Users\\USERNAME\\AppData\\Local\\Temp\\pip-install-l6bvkytm\\scikit-umfpack\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\USERNAME\AppData\Local\Temp\pip-record-iwvssjic\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\tools\Anaconda3\envs\p37_pip\Include\scikit-umfpack' Check the logs for full command output.
```

which seems to be related to https://github.com/scikit-umfpack/scikit-umfpack/pull/52

This is as far as I have investigated for now.

**Comment by constructor-s** [comment]
Seeing the instructions at: https://scikit-umfpack.github.io/scikit-umfpack/install.html

I have generated the following configuration under `%USERPROFILE%/.numpy-site.cfg`, with https://github.com/numpy/numpy/blob/master/site.cfg.example as a template

```ini
[amd]
library_dirs = C:\vcpkg\installed\x64-windows\lib
include_dirs = C:\vcpkg\installed\x64-windows\include\suitesparse
amd_libs = libamd

[umfpack]
library_dirs = C:\vcpkg\installed\x64-windows\lib
include_dirs = C:\vcpkg\installed\x64-windows\include\suitesparse
umfpack_libs = libumfpack
```

I am not sure if the "lib" prefix is necessary, but it works. 

Right now it still complains that it does not find BLAS but seems to work fine for now?

PS: Somehow if I list multiple includes_dir separate by comma it doesn't work... Anyone knows what is the proper syntax?

**Comment by kanthagirish** [comment]
> Seeing the instructions at: https://scikit-umfpack.github.io/scikit-umfpack/install.html I have generated the following configuration under `%USERPROFILE%/.numpy-site.cfg`, with https://github.com/numpy/numpy/blob/master/site.cfg.example as a template and installed with `pip install git+git://github.com/scikit-umfpack/scikit-umfpack.git --log log.txt`
> 
> ```ini
> [amd]
> library_dirs = C:\vcpkg\installed\x64-windows\lib
> include_dirs = C:\vcpkg\installed\x64-windows\include\suitesparse
> amd_libs = libamd
> 
> [umfpack]
> library_dirs = C:\vcpkg\installed\x64-windows\lib
> include_dirs = C:\vcpkg\installed\x64-windows\include\suitesparse
> umfpack_libs = libumfpack
> ```
> 
> I am not sure if the "lib" prefix is necessary, but it works.
> 
> Right now it still complains that it does not find BLAS but seems to work fine for now? Can we fix the wheel on PyPI?
> 
> PS: Somehow if I list multiple includes_dir separate by comma it doesn't work... Anyone knows what is the proper syntax?

@constructor-s I tried something similar. However, I keep running into `error: don't know how to set runtime library search path for MSVC` when I try to compile. Any ideas how to solve this?

The multiple includes_dir didn't work for me either. So I added a new section for blas in the configuration with `library_dirs` set to the path containing blas DLLs. That seems to work
