### ISSUE TITLE
Install Error of scikit-umfpack

### ISSUE THREAD

**Issue by yJesseChen** [scikit-umfpack/scikit-umfpack#66]
I tried to install scikit-umfpack on google colab with an environment of python [3.7.10] by
`! pip install --upgrade scikit-umfpack`

But it came with an error:

`Collecting scikit-umfpack 
  Using cached scikit-umfpack-0.3.2.tar.gz (25 kB)
  Requirement already satisfied: numpy>=1.19.5 in /usr/local/lib/python3.7/dist-packages (from scikit-umfpack) (1.19.5)
  Requirement already satisfied: scipy>=1.0.0rc1 in /usr/local/lib/python3.7/dist-packages (from scikit-umfpack) (1.4.1)
  
  Building wheels for collected packages: scikit-umfpack
  Building wheel for scikit-umfpack (setup.py) ... error
  ERROR: Failed building wheel for scikit-umfpack
  
  Running setup.py clean for scikit-umfpack
  Failed to build scikit-umfpack
  Installing collected packages: scikit-umfpack
    Running setup.py install for scikit-umfpack ... error
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-jg9e_5m1/scikit-umfpack_57080a1d682b48229f0411110cd8e668/setup.py'"'"'; __file__='"'"'/tmp/pip-install-jg9e_5m1/scikit-umfpack_57080a1d682b48229f0411110cd8e668/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-_ic_5q50/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.7/scikit-umfpack Check the logs for full command output.
`

Is there any problem with my code? (I think google colab is sort of 'standard' environment with required packages)

**Comment by guyumengyue** [comment]
Have you resolved the situation? I hava the same problem as you.

Building wheels for collected packages: scikit-umfpack
  Building wheel for scikit-umfpack (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/wzl/anaconda3/envs/Python38/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-oigeu_iu/scikit-umfpack_6e69f6269f1e4ee4b61df29d6d317d8d/setup.py'"'"'; __file__='"'"'/tmp/pip-install-oigeu_iu/scikit-umfpack_6e69f6269f1e4ee4b61df29d6d317d8d/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-mmf2nth4
       cwd: /tmp/pip-install-oigeu_iu/scikit-umfpack_6e69f6269f1e4ee4b61df29d6d317d8d/
  Complete output (32 lines):
  /tmp/pip-install-oigeu_iu/scikit-umfpack_6e69f6269f1e4ee4b61df29d6d317d8d/setup.py:56: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
    import imp
  INFO: umfpack_info:
  INFO: customize UnixCCompiler
  INFO:   libraries umfpack not found in ['/home/wzl/anaconda3/envs/Python38/lib', '/usr/local/lib', '/usr/lib']
  /home/wzl/anaconda3/envs/Python38/lib/python3.8/site-packages/numpy/distutils/system_info.py:585: UserWarning:
      UMFPACK sparse solver (https://www.cise.ufl.edu/research/sparse/umfpack/)
      not found. Directories to search for the libraries can be specified in the
      numpy/distutils/site.cfg file (section [umfpack]) or by setting
      the UMFPACK environment variable.
    return cl().get_info(notfound_action)
  INFO:   NOT AVAILABLE
  INFO:
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-oigeu_iu/scikit-umfpack_6e69f6269f1e4ee4b61df29d6d317d8d/setup.py", line 250, in <module>
      setup_package()
    File "/tmp/pip-install-oigeu_iu/scikit-umfpack_6e69f6269f1e4ee4b61df29d6d317d8d/setup.py", line 247, in setup_package
      setup(**metadata)
    File "/home/wzl/anaconda3/envs/Python38/lib/python3.8/site-packages/numpy/distutils/core.py", line 135, in setup
      config = configuration()
    File "/tmp/pip-install-oigeu_iu/scikit-umfpack_6e69f6269f1e4ee4b61df29d6d317d8d/setup.py", line 143, in configuration
      config.add_subpackage('scikits.umfpack')
    File "/home/wzl/anaconda3/envs/Python38/lib/python3.8/site-packages/numpy/distutils/misc_util.py", line 1054, in add_subpackage
      config_list = self.get_subpackage(subpackage_name, subpackage_path,
    File "/home/wzl/anaconda3/envs/Python38/lib/python3.8/site-packages/numpy/distutils/misc_util.py", line 1020, in get_subpackage
      config = self._get_configuration_from_setup_py(
    File "/home/wzl/anaconda3/envs/Python38/lib/python3.8/site-packages/numpy/distutils/misc_util.py", line 962, in _get_configuration_from_setup_py
      config = setup_module.configuration(*args)
    File "scikits/umfpack/setup.py", line 19, in configuration
      umf_info['libraries'].insert(0, 'rt')
  KeyError: 'libraries'
  ----------------------------------------
  ERROR: Failed building wheel for scikit-umfpack
  Running setup.py clean for scikit-umfpack
Failed to build scikit-umfpack
Installing collected packages: xgboost, torchvision, scikit-umfpack, scikit-learn, pytorch-lightning, pandas, optuna, cvxpy, mlopt
    Running setup.py install for scikit-umfpack ... error
    ERROR: Command errored out with exit status 1:
     command: /home/wzl/anaconda3/envs/Python38/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-oigeu_iu/scikit-umfpack_6e69f6269f1e4ee4b61df29d6d317d8d/setup.py'"'"'; __file__='"'"'/tmp/pip-install-oigeu_iu/scikit-umfpack_6e69f6269f1e4ee4b61df29d6d317d8d/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-zo0gtneo/install-record.txt --single-version-externally-managed --compile --install-headers /home/wzl/anaconda3/envs/Python38/include/python3.8/scikit-umfpack
         cwd: /tmp/pip-install-oigeu_iu/scikit-umfpack_6e69f6269f1e4ee4b61df29d6d317d8d/
    Complete output (32 lines):
    /tmp/pip-install-oigeu_iu/scikit-umfpack_6e69f6269f1e4ee4b61df29d6d317d8d/setup.py:56: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
      import imp
    INFO: umfpack_info:
    INFO: customize UnixCCompiler
    INFO:   libraries umfpack not found in ['/home/wzl/anaconda3/envs/Python38/lib', '/usr/local/lib', '/usr/lib']
    /home/wzl/anaconda3/envs/Python38/lib/python3.8/site-packages/numpy/distutils/system_info.py:585: UserWarning:
        UMFPACK sparse solver (https://www.cise.ufl.edu/research/sparse/umfpack/)
        not found. Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [umfpack]) or by setting
        the UMFPACK environment variable.
      return cl().get_info(notfound_action)
    INFO:   NOT AVAILABLE
    INFO:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-oigeu_iu/scikit-umfpack_6e69f6269f1e4ee4b61df29d6d317d8d/setup.py", line 250, in <module>
        setup_package()
      File "/tmp/pip-install-oigeu_iu/scikit-umfpack_6e69f6269f1e4ee4b61df29d6d317d8d/setup.py", line 247, in setup_package
        setup(**metadata)
      File "/home/wzl/anaconda3/envs/Python38/lib/python3.8/site-packages/numpy/distutils/core.py", line 135, in setup
        config = configuration()
      File "/tmp/pip-install-oigeu_iu/scikit-umfpack_6e69f6269f1e4ee4b61df29d6d317d8d/setup.py", line 143, in configuration
        config.add_subpackage('scikits.umfpack')
      File "/home/wzl/anaconda3/envs/Python38/lib/python3.8/site-packages/numpy/distutils/misc_util.py", line 1054, in add_subpackage
        config_list = self.get_subpackage(subpackage_name, subpackage_path,
      File "/home/wzl/anaconda3/envs/Python38/lib/python3.8/site-packages/numpy/distutils/misc_util.py", line 1020, in get_subpackage
        config = self._get_configuration_from_setup_py(
      File "/home/wzl/anaconda3/envs/Python38/lib/python3.8/site-packages/numpy/distutils/misc_util.py", line 962, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "scikits/umfpack/setup.py", line 19, in configuration
        umf_info['libraries'].insert(0, 'rt')
    KeyError: 'libraries'
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/wzl/anaconda3/envs/Python38/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-oigeu_iu/scikit-umfpack_6e69f6269f1e4ee4b61df29d6d317d8d/setup.py'"'"'; __file__='"'"'/tmp/pip-install-oigeu_iu/scikit-umfpack_6e69f6269f1e4ee4b61df29d6d317d8d/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-zo0gtneo/install-record.txt --single-version-externally-managed --compile --install-headers /home/wzl/anaconda3/envs/Python38/include/python3.8/scikit-umfpack Check the logs for full command output.

**Comment by yJesseChen** [comment]
@guyumengyue , I guess the author did not update the package since Python 3.6.2. So I just use scipy under environment 3.6.2 when I want to use umfpack. It works for me on Mac and CentOS.

**Comment by guyumengyue** [comment]
Thank you so much for helping me!

**Comment by bnavigator** [comment]
Your pip tries to build a wheel from source because the last published wheel on PyPI is for Python 3.6. This package works for Python 3.10, but you need to have the UMFPACK library from SuiteSparse in order to compile the package. (See README).
