### ISSUE TITLE
scikit-umfpack 0.3.2

### ISSUE THREAD

**Issue by guyumengyue** [scikit-umfpack/scikit-umfpack#67]
>>>from scikits.umfpack import spsolve, splu
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "e:\users\wzl\anaconda3\pkgs\scikit-umfpack-master\scikits\umfpack\__init__.py", line 12, in <module>
    from .umfpack import *
  File "e:\users\wzl\anaconda3\pkgs\scikit-umfpack-master\scikits\umfpack\umfpack.py", line 130, in <module>
    from . import _umfpack as _um
ImportError: cannot import name '_umfpack' from partially initialized module 'scikits.umfpack' (most likely due to a circular import) (e:\users\wzl\anaconda3\pkgs\scikit-umfpack-master\scikits\umfpack\__init__.py)

What should I do to solve this problem?

**Comment by guyumengyue** [comment]
Resolved. Only version 0.3.1 works and only on Python 3.6 (Windows 10 x64) #64
