### ISSUE TITLE
Module not found error when importing umfpack MacOS Monterey M1 chip

### ISSUE THREAD

**Issue by cta2106** [scikit-umfpack/scikit-umfpack#71]
I installed **umfpack** using `pip install scikit-umfpack` and tried importing the umfpack module

>`from scikits import umfpack`

I'm running into the following error:
```
Traceback (most recent call last):
  File "/Users/christianadib/pyfrbus_package/venv/lib/python3.9/site-packages/scikits/umfpack/_umfpack.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('__umfpack', [dirname(__file__)])
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '__umfpack'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/christianadib/pyfrbus_package/venv/lib/python3.9/site-packages/scikits/umfpack/__init__.py", line 12, in <module>
    from .umfpack import *
  File "/Users/christianadib/pyfrbus_package/venv/lib/python3.9/site-packages/scikits/umfpack/umfpack.py", line 130, in <module>
    from . import _umfpack as _um
  File "/Users/christianadib/pyfrbus_package/venv/lib/python3.9/site-packages/scikits/umfpack/_umfpack.py", line 28, in <module>
    __umfpack = swig_import_helper()
  File "/Users/christianadib/pyfrbus_package/venv/lib/python3.9/site-packages/scikits/umfpack/_umfpack.py", line 20, in swig_import_helper
    import __umfpack
ModuleNotFoundError: No module named '__umfpack'

```

**Comment by cmutel** [comment]
The readme states clearly that you need to install `suitesparse` before this library. Here is what worked for me:

1. Install homebrew
2. `brew install swig suite-sparse`
3. Create a config file with the location of the files homebrew just installed. It is a `.ini` file, the name doesn't matter; I used `custom-config.ini`:

```
[properties]
umfpack-libdir = '/opt/homebrew/Cellar/suite-sparse/7.6.0/lib/'
umfpack-includedir = '/opt/homebrew/Cellar/suite-sparse/7.6.0/include/suitesparse/'
```

This assumes you install version 7.6.0.

4. Install `scikit-umfpack` and tell it where the config file is:

```console
pip install scikit-umfpack -Csetup-args=--native-file=$PWD/custom-config.ini
```

This assumes that the `custom-config.ini` file is in your current working directory.
