### ISSUE TITLE
pip install scikit-umfpack fails on latest pip (23.1.2)

### ISSUE THREAD

**Issue by rachtsingh** [scikit-umfpack/scikit-umfpack#81]
I was able to downgrade to install it successfully, but it's probably worth fixing for other users (leaving this here for others):

```
user@ip-172-31-26-29:/data/tools/envs/checkout$ python -m pip install --upgrade scikit-umfpack scikit-sparse
Collecting scikit-umfpack
  Using cached scikit-umfpack-0.3.3.tar.gz (26 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      <string>:56: DeprecationWarning: the imp module is deprecated in favour of importlib and slated for removal in Python 3.12; see the module's documentation for alternative uses
      Traceback (most recent call last):
        File "/data/tools/envs/pyenv/versions/3.10.4/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/data/tools/envs/pyenv/versions/3.10.4/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/data/tools/envs/pyenv/versions/3.10.4/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "/tmp/pip-build-env-_vsnchoq/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 380, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/tmp/pip-build-env-_vsnchoq/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 487, in run_setup
          super(_BuildMetaLegacyBackend,
        File "/tmp/pip-build-env-_vsnchoq/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 250, in <module>
        File "<string>", line 243, in setup_package
      ModuleNotFoundError: No module named 'numpy'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
user@ip-172-31-26-29:/data/tools/envs/checkout$ pip --version
pip 23.1.2 from /data/tools/envs/pyenv/versions/3.10.4/lib/python3.10/site-packages/pip (python 3.10)
user@ip-172-31-26-29:/data/tools/envs/checkout$ python -m pip install pip==22.3
Collecting pip==22.3
  Downloading pip-22.3-py3-none-any.whl (2.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 49.2 MB/s eta 0:00:00
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 23.1.2
    Uninstalling pip-23.1.2:
      Successfully uninstalled pip-23.1.2
Successfully installed pip-22.3
user@ip-172-31-26-29:/data/tools/envs/checkout$ python -m pip install --upgrade scikit-umfpack scikit-sparse
Collecting scikit-umfpack
  Using cached scikit-umfpack-0.3.3.tar.gz (26 kB)
  Preparing metadata (setup.py) ... done
Collecting scikit-sparse
  Downloading scikit-sparse-0.4.8.tar.gz (209 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 209.7/209.7 kB 8.5 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: numpy>=1.24.3 in /data/tools/envs/pyenv/versions/3.10.4/lib/python3.10/site-packages (from scikit-umfpack) (1.24.3)
Requirement already satisfied: scipy>=1.0.0rc1 in /data/tools/envs/pyenv/versions/3.10.4/lib/python3.10/site-packages (from scikit-umfpack) (1.10.1)
Building wheels for collected packages: scikit-sparse
  Building wheel for scikit-sparse (pyproject.toml) ... done
  Created wheel for scikit-sparse: filename=scikit_sparse-0.4.8-cp310-cp310-linux_x86_64.whl size=737506 sha256=9c9cb902f2d88897e0106b06237cd133bbf10d59a579cdb4d5f38fe29ae509a8
  Stored in directory: /home/user/.cache/pip/wheels/8f/bf/e4/e5abcbfb0d77d47e365515f13cda178c32f88cdce66342c850
Successfully built scikit-sparse
Installing collected packages: scikit-umfpack, scikit-sparse
  DEPRECATION: scikit-umfpack is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
  Running setup.py install for scikit-umfpack ... done
Successfully installed scikit-sparse-0.4.8 scikit-umfpack-0.3.3

[notice] A new release of pip available: 22.3 -> 23.1.2
[notice] To update, run: pip install --upgrade pip
user@ip-172-31-26-29:/data/tools/envs/checkout$
```

**Comment by mike-kfed** [comment]
I can confirm this issue. if somebody runs into this using poetry here's how I fixed it

```bash
# downgrade pip
poetry run pip install pip==22.3
# manually install umfpack
poetry run pip install scikit-umfpack
# finish installing the rest
poetry install
```

**Comment by mike-kfed** [comment]
In hindsight I think that the actual fix is the existence of `pyproject.toml`, which is available when the package is installed from git-source. It might need to be added the .tgz release package, to actually fix this issue?

**Comment by rc** [comment]
Then I will add it to `MANIFEST.in`.
