### ISSUE TITLE
pip install on Python 3.12 fails

### ISSUE THREAD

**Issue by 2sn** [scikit-umfpack/scikit-umfpack#89]
When I ty to install `scikit-umfpack` on Python 3.12 I get the following error message:
```
~>pip3 install scikit-umfpack
Collecting scikit-umfpack
  Using cached scikit-umfpack-0.3.3.tar.gz (26 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      Traceback (most recent call last):
        File "/home/alex/Python/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/alex/Python/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/alex/Python/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-g2d79gik/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 355, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-g2d79gik/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 325, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-g2d79gik/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 507, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-g2d79gik/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 250, in <module>
        File "<string>", line 151, in setup_package
        File "<string>", line 79, in write_version_py
        File "<string>", line 56, in get_version_info
      ModuleNotFoundError: No module named 'imp'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```
I use Python 3.12.0 installed from source on Fedora 38 Linux.

**Comment by cmutel** [comment]
This was fixed in 02c8d01c7e4e1229f2278b1d7fda3bd9edc1e69c, but needs a new release to be usable...

**Comment by 2sn** [comment]
Thanks.  Is there an ETA?

**Comment by rc** [comment]
I have tried to make a quick release, I was following [docs/release.rst](https://github.com/scikit-umfpack/scikit-umfpack/blob/master/docs/release.rst) (which needs updating for pytest etc.) up to the point 7, where my testpypi upload failed with:
```
$ pip install --no-deps --upgrade --pre -i https://testpypi.python.org/pypi scikit-umfpack
Looking in indexes: https://testpypi.python.org/pypi
Collecting scikit-umfpack
  Using cached https://test-files.pythonhosted.org/packages/71/e3/090e26312f7d52821569a80aa7903a005047ea37d2ed51fd395086b08ea0/scikit-umfpack-0.3.5.tar.gz (26 kB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error
  
  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [5 lines of output]
      Looking in indexes: https://testpypi.python.org/pypi
      Collecting wheel
        Using cached https://test-files.pythonhosted.org/packages/65/63/39d04c74222770ed1589c0eaba06c05891801219272420b40311cd60c880/wheel-0.36.2-py2.py3-none-any.whl (35 kB)
      ERROR: Could not find a version that satisfies the requirement setuptools (from versions: none)
      ERROR: No matching distribution found for setuptools
      [end of output]
```
This package still uses the deprecated `numpy.distutils`, so it is probably related. Is there a simple solution, or a new build system is needed?

**Comment by rgommers** [comment]
That does not look like a simple fix, a build system switch is needed I'm afraid. There's three things from `numpy.distutils` that you're using:
1. `Configuration` (nested setup.py files)
2. UMFPACK detection, and
3. BLAS support.

(1) isn't really needed, but there's no easy way to get  (2) and (3) from plain `setuptools`. It's also uncomfortable to do without CI, so adding at least one new CI job that exercises the new build system would make sense. It'd probably take me an hour or two to switch things over to Meson and `meson-python`. I don't think I have time the coming week to do that though. If you or anyone else wants to take a stab at it, I can add some pointers though.

**Comment by rc** [comment]
Hi Ralf,

Thanks for chiming in! I could try giving it a shot, provided your adding pointers that I could follow does not exceed the time taking you to actually do it :)

**Comment by rgommers** [comment]
Great! Here's how I'd start:
- You need to update `pyproject.toml` and add a top-level `meson.build` file. I recently helped another small project, `scs-python` with that - it also depends on both NumPy and BLAS, so it'll look quite similar. You can copy from https://github.com/bodono/scs-python/pull/70/
- To detect UMFPACK, you want to use `cc.find_library` with the appropriate library and header names. See https://mesonbuild.com/Reference-manual_returned_compiler.html#compilerfind_library. (note; you can't use `dependency()` in Meson for UMFPACK I believe, because SuiteSparse doesn't ship the needed pkg-config or CMake files).
- Keep in mind that:
    - You'll have to explicitly list the `.py` files to install with `py.install_sources(...)`, no globbing.
    - Meson will by default install the extension modules and Python files in the same directory as the `meson.build` file that the relevant install commands are in. So you want to nest them, using `subdir(...)` - similar to the nested `setup.py` files you already have.
- A CI job should be pretty straightforward. Maybe use a venv and rely on `pip install . -v` to use build isolation (ensures `pyproject.toml` is right - e.g., like so: https://github.com/scipy/scipy/blob/930fac3811bfd57b4375ac3a02a4abc1ce4cbda7/.github/workflows/linux_meson.yml#L125-L157

**Comment by DrTimothyAldenDavis** [comment]
SuiteSparse is getting a new cmake build system, thanks to @mmuetzel.  It  will have both pkg-config files and a cmake system.  You can now do "find_package ( UMFPACK 6.2 REQUIRED )", etc, with the latest SuiteSparse version.

**Comment by rgommers** [comment]
Great, that should be useful in the near future, thanks @DrTimothyAldenDavis and @mmuetzel!

**Comment by rc** [comment]
I have been trying to put together a basic meson.build file, but it went poorly so far - searching examples of how to use swig.

**Comment by rgommers** [comment]
You simply want to invoke swig as a code generator, right? And then add the generated C++ source files to your extension module? If so, it should be pretty much the same as how we use `pythran` in SciPy. To find `swig`:
```meson
swig = find_program('swig', native: true)
```
and then to use it:

https://github.com/scipy/scipy/blob/d7f12d38b171f3a6ae841937bb6c2444a1e04b8d/scipy/interpolate/meson.build#L164-L177

**Comment by rc** [comment]
Thanks! I can now run swig to generate the wrapper C code. Now I am stuck again, but I will create a PR so that you could eventually have a look.

**Comment by rc** [comment]
The new release 0.4.0 is available from PyPi. Thanks @rgommers for making this possible!
